project_id = "qkohrpediveghhtfkyaq"

[auth]
enabled = true
site_url = "https://qkohrpediveghhtfkyaq.lovable.app"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external]

[functions.send-booking-notification]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.create-payment]
verify_jwt = false