// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkohrpediveghhtfkyaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrb2hycGVkaXZlZ2hodGZreWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTgwNDAsImV4cCI6MjA2ODc3NDA0MH0.sguwoAvMTyrYD-0O5J3EKVYNqriGzi7VXBfXYANlQPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});